### ISSUE TITLE
Details on usage?

### ISSUE THREAD

**Issue by noobtoob4lyfe** [GregoryKogan/algo-vfi#1]
How does one go about using your fantastic work?  The readme is missing instructions

**Comment by GregoryKogan** [comment]
I'm sorry for the late reply. This is code for an educational research project and is not intended for any practical use. However you can find an example of usage in the [`vfi/src/tester.rs`](https://github.com/GregoryKogan/algo-vfi/blob/c986ed7884e843f72c49e768a12d7af4e6a5e243/vfi/src/tester.rs) file. It runs each implemented algorithm in turn.
